name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  cron:
    name:  Run every 5 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"